const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  feedbacks: [
    {
      id: 1,
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.',
      user: 'Anna K.',
      status: 'Furniture client',
      img: 'https://projects.kodilla.com/secure/useravatar?avatarId=10349',
    },
    {
      id: 2,
      text:
        'Fusce efficitur erat sodales purus tristique pulvinar. Proin et consequat urna. Quisque maximus interdum enim, nec sollicitudin nisi maximus in. Fusce facilisis, enim et sagittis.',
      user: 'Wojtek O.',
      status: 'Furniture client',
      img: 'https://projects.kodilla.com/secure/useravatar?avatarId=10352',
    },
    {
      id: 3,
      text:
        'ras rhoncus dapibus nisi, at placerat velit interdum sed. Suspendisse pharetra venenatis sapien, quis porta nunc accumsan quis. Proin blandit rhoncus pharetra. Ut nec semper.',
      user: 'Patryk T.',
      status: 'Super client',
      img: 'https://projects.kodilla.com/secure/useravatar?avatarId=10350',
    },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 40,
      stars: 1,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://www.fortywinks.com.au/getmedia/f4614e1e-9b00-476b-bdcd-e28afa3d34db/jackson_bed_frame-front.jpg?width=1200',
      favorites: true,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images-na.ssl-images-amazon.com/images/I/817%2BqPbDo8L._SX425_.jpg',
      favorites: false,
      compare: false,
      myStars: 4,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202040/0168/anton-solid-wood-bed-o.jpg',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://ii1.pepperfry.com/media/catalog/product/k/o/1100x1210/kosmo-new-port-queen-size-bed-with-storage-in-vermount-finish-by-spacewood-kosmo-new-port-queen-size-tiaya2.jpg',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: 35,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3753435/pexels-photo-3753435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3773581/pexels-photo-3773581.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1879061/pexels-photo-1879061.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4119831/pexels-photo-4119831.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3144580/pexels-photo-3144580.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2029731/pexels-photo-2029731.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2705/bed-bedroom-room-furniture.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4276617/pexels-photo-4276617.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3935331/pexels-photo-3935331.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3935353/pexels-photo-3935353.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3773577/pexels-photo-3773577.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/376531/pexels-photo-376531.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'banean-du-antique-1',
      name: 'Banean Du Antique 1',
      category: 'chair',
      price: 20,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'banean-du-antique-2',
      name: 'Banean Du Antique 2',
      category: 'chair',
      price: 20,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1321290/pexels-photo-1321290.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'banean-du-antique-3',
      name: 'Banean Du Antique 3',
      category: 'chair',
      price: 20,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/2180883/pexels-photo-2180883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'ulean-su-raqute-1',
      name: 'Ulean Su Raqute 1',
      category: 'sofa',
      price: 100,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'ulean-su-raqute-2',
      name: 'Ulean Su Raqute 2',
      category: 'sofa',
      price: 100,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'ulean-su-raqute-3',
      name: 'Ulean Su Raqute 3',
      category: 'sofa',
      price: 100,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4352247/pexels-photo-4352247.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'argean-la-fata-1',
      name: 'Argean La Fata 1',
      category: 'table',
      price: 50,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/890669/pexels-photo-890669.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'argean-la-fata-2',
      name: 'Argean La Fata 2',
      category: 'table',
      price: 50,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/842950/pexels-photo-842950.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'argean-la-fata-3',
      name: 'Argean La Fata 3',
      category: 'table',
      price: 50,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/280471/pexels-photo-280471.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'dagadan-ge-jala-1',
      name: 'Dagadan Ge Jala 1',
      category: 'dining',
      price: 60,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'dagadan-ge-jala-2',
      name: 'Dagadan Ge Jala 2',
      category: 'dining',
      price: 60,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
    {
      id: 'dagadan-ge-jala-3',
      name: 'Dagadan Ge Jala 3',
      category: 'dining',
      price: 60,
      oldPrice: null,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image:
        'https://images.pexels.com/photos/4577410/pexels-photo-4577410.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      favorites: false,
      compare: false,
      myStars: 0,
    },
  ],
  cart: {
    products: [],
  },

  Promotion: {
    sofa:
      'https://images.pexels.com/photos/3757055/pexels-photo-3757055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    firstChair:
      'https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    secondChair:
      'https://images.pexels.com/photos/2180883/pexels-photo-2180883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    bed:
      'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text1a: 'GUEST ROOM',
    text1b: 'SOFA',
    textbargain: '-20%',
    text2a: 'OFFICE ',
    text2b: 'CHAIR',
    text2c: 'COLLECTION',
    textPrice: '$200.00',
    text3a: 'SPECIAL',
    text3b: 'COLLECTION',
    textInfo: 'SAVE UP 45% OF FURNITURE',
  },
  brand: {
    image1:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/eab093a0a25c7994ab8cc0b64eaadd00.png',
    image2:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/01273596e4e92b9de8e8a11cd4ed455e.png',
    image3:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/71a9c6a80e57e1ee631a929191346262.png',
    image4:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/c3a241ae6d1e03513dfed6f5061f4a4b.png',
    image5:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/e1179e27ce0f55a3bd31d92e9c751731.png',
    image6:
      'https://cdn.shopify.com/shopifycloud/hatchful-web/assets/5d6266e7bbcdb8fb017c10000ead2fd3.png',
    image7: 'https://image.freepik.com/free-vector/fashion-logo_23-2148558723.jpg',
    image8:
      'https://image.freepik.com/free-vector/fashion-shop-logo-template_23-2148593858.jpg',
    image9:
      'https://image.freepik.com/free-vector/fashion-brand-logo-template-with-tagline_23-2148661989.jpg',
    image10: 'https://image.freepik.com/free-psd/dark-fashion-logo-mock-up_1097-15.jpg',
    image11: 'https://image.freepik.com/free-vector/vintage-boutique-logo_1057-438.jpg',
    image12: 'https://image.freepik.com/free-vector/butterfly-logo-icon_126523-249.jpg',
    image13:
      'https://image.freepik.com/free-vector/luxury-boutique-logo-templates_15146-127.jpg',
    image14:
      'https://image.freepik.com/free-vector/hipster-design-studio-logo-vector_53876-40513.jpg',
    image15:
      'https://image.freepik.com/free-vector/elegant-circle-logo-icon_126523-971.jpg',
  },
};

export default initialState;
